@startuml
' https://plantuml.com/class-diagram

package vehicle {
    class Vehicle {
        # String plateNumber
        # String make
        # String model
        # int year
        # Client leasedBy
        + getPlateNumber(): String
        + getMake(): String
        + getModel(): String
        + getYear(): int
        + setMake(String make)
        + setModel(String model)
        + setYear(int year)
        + isLeased(): boolean
        + leaseTo(Client client)
        + returnVehicle()
        + toString(): String
        + equals(Object obj): boolean
    }

    class Car extends Vehicle {
        # int maxPassengers
        + getMaxPassengers(): int
        + setMaxPassengers(int maxPassengers)
        + toString(): String
        + equals(Object obj): boolean
    }

    class Truck extends Vehicle {
        # int maxCapacity
        + getMaxCapacity(): int
        + setMaxCapacity(int maxCapacity)
        + toString(): String
        + equals(Object obj): boolean
    }

    class ElectricCar extends Car {
        - int autonomyRange
        + getAutonomyRange(): int
        + setAutonomyRange(int autonomyRange)
        + toString(): String
        + equals(Object obj): boolean
    }

    class GasolineCar extends Car {
        + toString(): String
        + equals(Object obj): boolean
    }

    class ElectricTruck extends Truck {
        - int autonomyRange
        + getAutonomyRange(): int
        + setAutonomyRange(int autonomyRange)
        + toString(): String
        + equals(Object obj): boolean
    }

    class DieselTruck extends Truck {
        - int fuelTankCapacity
        + getFuelTankCapacity(): int
        + setFuelTankCapacity(int fuelTankCapacity)
        + toString(): String
        + equals(Object obj): boolean
    }
}

package client {
    class Client {
        - String name
        - String id
        + getName(): String
        + setName(String name)
        + getId(): String
        + setId(String id)
        + toString(): String
        + equals(Object obj): boolean
    }
}

' Association: Each Vehicle may be leased by a Client.
Vehicle --> Client : leasedBy

@enduml